automation:
  - id: "zigbee_router_unavailable"
    initial_state: on
    alias: "Zigbee Router Unavailable"
    trigger:
      - trigger: state
        entity_id:
          - switch.kitchen_water_pump
          - sswitch.office_outlet_1
        to: "unavailable"
        for:
          minutes: 15
    action:
      - action: script.general_notification
        data:
          title: "Zigbee System Issue"
          message: "There is an issue with the following Zigbee routers: {{ trigger.to_state.attributes.friendly_name }}"
          devices: "rick_all"
          priority: "time-sensitive"
          tag: "d"