automation:
  # Automation to detect if the house is now not occupied
  #
  # This automation will detect if the house is occupied
  # based on a few triggers and conditions
  # and if it's occupied, it will update the
  # input_boolean.house_occupied to be on
  #
  - id: "house_not_occupied"
    alias: "House not occupied"
    initial_state: true
    trigger:
      # Triggered if John, Cristina, or Guest mode
      # get turned on
      - trigger: state
        entity_id:
          - input_boolean.rick_home
          - input_boolean.tracy_home
          - input_boolean.guest_mode
        to: "off"
      # Hassio reloads/starts
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    condition:
      # House is current occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "on"
      # Somebody is marked as home
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.rick_home
            state: "off"
          - condition: state
            entity_id: input_boolean.tracy_home
            state: "off"
          - condition: state
            entity_id: input_boolean.guest_mode
            state: "off"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.house_occupied